[package]
name = "stor"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
env_logger = "0.11.8"
fs_extra = "1.3.0"
home = "0.5.11"
log = "0.4.27"
